spring.application.name=pagamento

eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

server.forward-headers-strategy=native
server.servlet.context-path=/
spring.mvc.trailing-slash-match=false
spring.web.resources.add-mappings=false
